name: Create a PR to upgrade the crate to a new version

# Manually dispatch this action from the Actions page
on:
  workflow_dispatch:
    inputs:
      prev_version:
        description: 'Upgrading from version'
        required: true
        type: string
      next_version:
        description: 'Upgrading to version'
        required: true
        type: string

jobs:
  print-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print the versions
        run: echo Upgrading from ${{ inputs.prev_version }} to ${{ inputs.next_version }} 
